name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
      
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - name: MSYS2 Setup
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          make
          mingw-w64-x86_64-cairo
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-librsvg

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: make
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: inkscape
        path: |
          inkscape.exe
          *.dll
